pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven {url 'https://developer.huawei.com/repo/'}
        maven {url 'https://developer.hihonor.com/repo'}
        // 配置 vivo vpush SDK的Maven仓地址
        maven{ url 'https://repos.vivo.com.cn/maven/repository/external-lib/'}
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // 华为
        maven {url 'https://developer.huawei.com/repo/'}
        // 荣耀
        maven {url 'https://developer.hihonor.com/repo'}
        // JitPack 远程仓库：https://jitpack.io
        maven { url 'https://jitpack.io' }
        // oppo
        flatDir {
            dirs "$rootDir/app/libs"
        }
        // 配置 vivo vpush SDK的Maven仓地址
        maven{ url 'https://repos.vivo.com.cn/maven/repository/external-lib/'}
    }
}

rootProject.name = "Nsyy"
include ':app'
